#!/bin/bash

cd "/c/Program Files (x86)/Arduino/hardware/tools/avr/bin"

./avrdude.exe \
-C "C:\Program Files (x86)\Arduino\hardware\tools\avr/etc/avrdude.conf" \
-p atmega328p \
-c usbasp \
-U lfuse:w:0xA2:m \
-U hfuse:w:0xDF:m \
-U efuse:w:0xFD:m

