#!/bin/bash

"/c/Program Files (x86)/Arduino/hardware/tools/avr/bin/avrdude.exe" \
-C "C:\Program Files (x86)\Arduino\hardware\tools\avr/etc/avrdude.conf" \
-p atmega328p \
-c usbtiny \
-v \
-V \
-B30 -Uflash:w:AppPicoTracker1Config.2018-06-14.hex:i

